$           = require('jquery')
Handlebars  = require('handlebars')
Ember       = require('ember')
Emblem      = require('emblem')
DS          = require('ember-data')
pouchdb     = require('pouchdb')
DS.PouchDBSerializer = require('ember-pouchdb-adapter')
